### ISSUE TITLE
Plugin to conduct meetings

### ISSUE THREAD

**Issue by aperezdc** [aperezdc/luabot#2]
Similar behaviour as [MeetBot](https://wiki.debian.org/MeetBot) would be nice, to make it easier for people already used to it.

MeetBot command support:
- [x] `#startmeeting`
- [x] `#endmeeting`
- [x] `#chair`
- [x] `#unchair`
- [x] `#topic`
- [x] `#action`
- [x] `#info`
- [x] `#idea`
- [x] `#link`
- [x] `#help`
- [x] `#agreed`
- [x] `#accepted`
- [x] `#rejected`
- [x] `#undo`
- [x] `#nick`
- [x] `#lurk`
- [x] `#unlurk`
- [x] ~~`#meetingname`~~
- [x] ~~`#restrictlogs`~~
- [x] ~~`#meetingtopic`~~

MeetBot features:
- [x] Raw meeting log.
- [x] HTML meeting log.
- [x] ~~reStructuredText~~ Markdown meeting minutes.
- [x] HTML meeting minutes.

**Comment by tanty** [comment]
I suppose too ambitious but, maybe, better approach is to provide [Supybot](http://sourceforge.net/projects/supybot/) compatibility so we could use MeetBot or any other Supybot based bot.

**Comment by aperezdc** [comment]
@tanty The current plan is precisely that the meetings plugin for Luabot supports the same commands as MeetBot, with the same syntax, so it can be trated as a drop-in replacement. Supybot (and MeetBot, which builds on it) supports only IRC, and it is done in Python, so apart from being difficult to integrate, there's no much point provided that Luabot is using Verse already (n.b. Verse is a XMPP client framework derived from the extensively testes XMPP implementation of the [Prosody](http://prosody.im) XMPP server.)

**Comment by aperezdc** [comment]
The first pass at the meetings plugin now lives in the `master` branch. I have updated the issue description with a checklist of MeetBot features, so the implementation progress can be followed in a glance.

**Comment by aperezdc** [comment]
New update implementing most of the commands. Now there is only a few left (which I am not sure is worth implementing), and the missing generation of minutes and HTML logs. With the new data representation introduced by the last commit, it should be trivial to do the minutes.

**Comment by aperezdc** [comment]
HTML logs are now working, and they look like the MeetBot ones. Proof in this screen capture:

![screenshot from 2015-10-14 00-34-37](https://cloud.githubusercontent.com/assets/723451/10469282/df465178-720c-11e5-8a6b-c414ded50669.png)

**Comment by aperezdc** [comment]
I have added the admin commands to the list of MeetBot features, but probably it does not make sense to add support for them all. Also, adding them would need some additional settings for defining “bot admins”, either at the plug-in or bot level, so that's extra work. I may consider moving those to a new issue later on.

**Comment by aperezdc** [comment]
Moved the implementation of the admin commands to a separate issue (see #8). Also, the `#meetingname`, `#restrictlogs`, and `#meetingtopic` are non essential and the fact that a meeting title has to be given to `#startmeeting` makes `#meetingname` uneeded means that I will not be implementing them. Last, but not least, reStructuredText is very popular in the Python world, yes, but Markdown is more widespread and more tooling exists, so I am going to favor implementing a Markdown minutes generator instead.

**Comment by aperezdc** [comment]
Support for Markdown minutes is now in `master`, so I consider this issue done. For further improvements/bugs with the `meeting` plugin, please open new issues.
